class set_train_argument:
    def __init__(self,
                 lr: float = 5 * 1.0e-5,
                 projection_dims = 15,
                 l0_in_features: int = 1+15+15+1+1+4,
                 subset_size: int = 4,
                 edge_mode: str = 'dist',
                 drop_out = 0.1,
                 num_layers: int = 4,
                 use_energy: bool = False,
                 data_suffix = ".MT2",
                 use_l1_feature = False,
                 fix_random_seed = False,
                 w_loss_vdw = 1.0,
                 w_loss_elec = 1.0,
                 w_loss_solv = 1.0,
                 w_loss_rank = 1.0,
                 w_reg  = 1.0e-5,
                 ball_radius = 10,
                 edge_dist = (8.0, 4.5),                
                 all_cross = False,
                 backbone = "se3_transformer"):
        
        assert edge_mode in ['topk', 'dist', 'distT']
        self.lr = lr
        self.l0_in_features = l0_in_features
        self.subset_size = subset_size
        self.edge_mode = edge_mode
        self.use_energy = use_energy
        self.num_layers = num_layers
        self.data_suffix = data_suffix
        self.drop_out = drop_out
        self.use_l1_feature = use_l1_feature
        self.w_loss_vdw = w_loss_vdw
        self.w_loss_elec = w_loss_elec
        self.w_loss_solv = w_loss_solv
        self.w_reg = w_reg
        self.w_loss_rank = w_loss_rank
        self.ball_radius = ball_radius
        self.edge_dist = edge_dist
        self.fix_random_seed = fix_random_seed
        self.all_cross = all_cross
        self.projection_dims = projection_dims
        self.backbone = backbone


Energy_first_model_240129 = set_train_argument(lr = 0.5 * 1.0e-4,
                                            projection_dims = 20,
                                            l0_in_features = (1+20+20+1+1),
                                            subset_size = 4,
                                            edge_mode = 'dist',
                                            drop_out = 0.3,
                                            num_layers = 6,
                                            use_energy = False,
                                            data_suffix = '.MT_all',
                                            use_l1_feature = False,
                                            fix_random_seed = True,
                                            w_reg  = 5.0e-5,
                                            backbone = "egnn")

Energy_first_model_240130 = set_train_argument(lr = 0.5 * 1.0e-4,
                                            projection_dims = 20,
                                            l0_in_features = (1+20+20+1+1),
                                            subset_size = 4,
                                            edge_mode = 'dist',
                                            drop_out = 0.3,
                                            num_layers = 6,
                                            use_energy = False,
                                            data_suffix = '.MT_all',
                                            use_l1_feature = False,
                                            fix_random_seed = True,
                                            w_reg  = 5.0e-5,
                                            backbone = "egnn")

Energy_second_model_240130 = set_train_argument(lr = 0.5 * 1.0e-5,
                                            projection_dims = 17,
                                            l0_in_features = (1+17+17+1+1),
                                            subset_size = 4,
                                            edge_mode = 'dist',
                                            drop_out = 0.4,
                                            num_layers = 6,
                                            use_energy = False,
                                            data_suffix = '.MT_all',
                                            use_l1_feature = False,
                                            fix_random_seed = True,
                                            w_reg  = 5.0e-5,
                                            backbone = "egnn")

Energy_first_model_240202 = set_train_argument(lr = 0.5 * 1.0e-4,
                                            projection_dims = 22,
                                            l0_in_features = (1+22+22+1+1),
                                            subset_size = 4,
                                            edge_mode = 'dist',
                                            drop_out = 0.4,
                                            num_layers = 6,
                                            use_energy = False,
                                            data_suffix = '.MT_all',
                                            use_l1_feature = False,
                                            fix_random_seed = True,
                                            w_reg  = 5.0e-5,
                                            backbone = "egnn")

Energy_BallR12_240205 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.4,
                                    num_layers = 6,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius=12)

Energy_BallR10_240205 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.4,
                                    num_layers = 6,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius=10)

Energy_BallR9_240205 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.4,
                                    num_layers = 6,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius=9)

Energy_RmClash_240206 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_RmClash_lr01_240206 = set_train_argument(lr = 0.1 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_RmClash_lr2_240206 = set_train_argument(lr = 2 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

# Add ranking loss (pairwise marginal ranking loss) 24.02.08
Energy_Rank_240208 = set_train_argument(lr = 0.1 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 2.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL01_240208 = set_train_argument(lr = 0.1 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 0.1,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL1_240208 = set_train_argument(lr = 0.1 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 1.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL3_240208 = set_train_argument(lr = 0.1 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 3.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL5_240208 = set_train_argument(lr = 0.1 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 5.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

# Increase learning rate
Energy_Rank_RL1_Lr05_240209 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 1.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL1_Lr2_240209 = set_train_argument(lr = 2.0 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 1.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL1_Lr05_pd22_240209 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 22,
                                    l0_in_features = (1+22+22+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 1.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

# Modify ranking loss
Energy_Rank_RL15_Lr05_240210 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 1.5,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL2_Lr05_240210 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 2.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL25_Lr05_240210 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 2.5,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL3_Lr05_240210 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 3.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_Rank_RL4_Lr05_240210 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 4.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

## Add totol ranking loss
Energy_TotalRank_240211 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 1.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_TotalRank_LR2_240211 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 2.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_TotalRank_LR3_240211 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 3.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

Energy_TotalRank_LR3_Lr08_240211 = set_train_argument(lr = 0.8 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 3.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 5.0e-5,
                                    backbone = "egnn",
                                    ball_radius = 9)

# Remove reg_loss
Energy_TotalRank_NoReg_240212 = set_train_argument(lr = 0.5 * 1.0e-4,
                                    projection_dims = 20,
                                    l0_in_features = (1+20+20+1+1),
                                    subset_size = 4,
                                    edge_mode = 'dist',
                                    drop_out = 0.3,
                                    num_layers = 6,
                                    w_loss_elec = 1.5,
                                    w_loss_rank = 2.0,
                                    use_energy = False,
                                    data_suffix = '.MT_all',
                                    use_l1_feature = False,
                                    fix_random_seed = True,
                                    w_reg  = 0.0,
                                    backbone = "egnn",
                                    ball_radius = 9)

# SmoothL1 loss beta=0.1
Energy_TotalRank_NoReg_SmL1Beta01_240212 = set_train_argument(lr = 0.5 * 1.0e-4,
                                            projection_dims = 20,
                                            l0_in_features = (1+20+20+1+1),
                                            subset_size = 4,
                                            edge_mode = 'dist',
                                            drop_out = 0.3,
                                            num_layers = 6,
                                            w_loss_elec = 1.5,
                                            w_loss_rank = 2.0,
                                            use_energy = False,
                                            data_suffix = '.MT_all',
                                            use_l1_feature = False,
                                            fix_random_seed = True,
                                            w_reg  = 5.0e-5,
                                            backbone = "egnn",
                                            ball_radius = 9)